### ISSUE TITLE
Multi key keybinds can activate the wrong option.

### ISSUE THREAD

**Issue by geheur** [abextm/better-teleport-menu#4]
On my diary cape, my Jarr teleport is "J A" and my Two-pints teleport is "A". But, when I type "J A" it takes the Two-pints teleport (I assume because the Two-pints teleport is before the Jarr teleport in the list). I would expect "J A" to take me to the teleport I've assigned "J A" to (Jarr).

This also happens with say, "J Z X" and "Z X", or with "J Z X C" and "Z X".

**Comment by abextm** [comment]
fixed in 1d5e70bd987330fa42edb11ad568cdc32eec37b5

**Comment by ASong5** [comment]
I seem to still have this issue. For example, in my nexus I have troll stronghold set to "TROLL" and lumbridge set to "L". Trying to type "TROLL" brings me to lumby. Is this a bug or working how it's meant to?

**Comment by abextm** [comment]
So what is happening is it sees you have typed `TROL`, the `TROLL` keybind doesn't fully match the current state so it doesn't fire. The `L` keybind does match, so it fires. If you set it to just `TROL` it would take precedence, since they both match and `TROL` is longer than `L`. I'm not sure there is a great way for it to decide to ignore the matching `L` when there is a partial match for something else without making it act a bit weird.
